{% set name = "optional-lite" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinmoene/optional-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49b9deac842b3698fc9011b7678f943b4e36136e2ab711f535c1961ff2746e14

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}      # [ppc_arch != "p10"]
    - {{ compiler('cxx') }}    # [ppc_arch != "p10"]
    - cmake {{ cmake }}
    - ninja {{ ninja }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                           # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                     # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                           # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                     # [x86_64 and c_compiler_version == "7.2.*"]

test:
  commands:
    - test -f $PREFIX/include/nonstd/optional.hpp

about:
  home: https://github.com/martinmoene/optional-lite
  summary: A C++17-like optional, a nullable object for C++98, C++11 and later in a single-file header-only library
  license: BSL-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
